import { randomBytes } from "node:crypto";

/** A single agent operation (mirrors the device-agent grammar). */
export type Op = {
  type: string;
  config?: string;
  section?: string;
  section_type?: string;
  option?: string;
  value?: string;
  values?: Record<string, string>;
  list?: string[];
  name?: string;
  action?: string;
  // file.write / file.delete
  path?: string;
  content?: string;
  mode?: string;
};

export type RuleType =
  | "pause_device"
  | "block_domains_network"
  | "force_router_dns"
  | "block_managed_list"
  | "block_ip_set";

export type PauseDeviceParams = { mac: string; client_name?: string };
export type BlockDomainsParams = { domains: string[] };
export type ForceRouterDnsParams = Record<string, never>;
/**
 * A snapshot of a curated upstream blocklist. We don't store the whole list
 * in params (it's ~17k entries / ~600KB) — just the source identifier and a
 * timestamp. The current snapshot is fetched at apply time and dropped into
 * a single dnsmasq conf file on the router via a `file.write` op.
 */
export type BlockManagedListParams = {
  source: "hagezi-anti-bypass";
  snapshot_at: string; // ISO timestamp of when the source was last fetched
  domain_count: number;
};
/**
 * Firewall-layer block of an upstream IP list. Generates a tiny nftables
 * include (`/etc/nftables.d/bt-<id>.nft`) with a `set` of addresses + a
 * forward-hook chain at priority -10 (fires before fw4's main filter chain
 * at priority 0) that REJECTs matching outbound traffic.
 */
export type BlockIpSetParams = {
  source: "dibdot-doh-ipv4" | "dibdot-doh-ipv6" | "tor-exit-ipv4";
  // If set, only block traffic to this port; otherwise block any port.
  // DoH typically only matters on 443. Tor uses many ports → omit.
  dest_port?: number;
  snapshot_at: string;
  ip_count: number;
};
export type RuleParams =
  | PauseDeviceParams
  | BlockDomainsParams
  | ForceRouterDnsParams
  | BlockManagedListParams
  | BlockIpSetParams;

export interface AccountRule {
  rule_id: string;
  rule_type: RuleType;
  params: RuleParams;
  ops: Op[];
  name: string;
  summary?: string;
  active: boolean;
}

export function newRuleId(
  prefix: "pause" | "domains" | "dnsforce" | "mlist" | "ipset",
): string {
  return `${prefix}_${randomBytes(4).toString("hex")}`;
}

/** Path on the router for a managed-list rule's dnsmasq conf snippet. */
export function managedListConfPath(ruleId: string): string {
  return `/etc/dnsmasq.d/bt-${ruleId}.conf`;
}

/** Path on the router for a block_ip_set rule's nftables include. */
export function ipSetNftPath(ruleId: string): string {
  return `/etc/nftables.d/bt-${ruleId}.nft`;
}

/**
 * What a rule "owns" on the device. Cleanup removes every owned target
 * regardless of whether the rule is active right now — that's how a
 * transition from active→inactive actually drops state on the router.
 *
 *   - kind:"uci"  → a named UCI section (`bt_<ruleId>[_suffix]`)
 *   - kind:"file" → a file on the router (managed-list rules use one
 *                   dnsmasq conf snippet per rule under /etc/dnsmasq.d/)
 */
export type CleanupTarget =
  | { kind: "uci"; config: string; section: string }
  | { kind: "file"; path: string };

export function ownedTargets(
  ruleId: string,
  type: RuleType,
): CleanupTarget[] {
  switch (type) {
    case "pause_device":
      return [{ kind: "uci", config: "firewall", section: `bt_${ruleId}` }];
    case "block_domains_network":
      return []; // owns dnsmasq address list entries, wiped by assembleDesired
    case "force_router_dns":
      return [
        { kind: "uci", config: "firewall", section: `bt_${ruleId}_t` },
        { kind: "uci", config: "firewall", section: `bt_${ruleId}_u` },
        { kind: "uci", config: "firewall", section: `bt_${ruleId}_dot` },
      ];
    case "block_managed_list":
      return [{ kind: "file", path: managedListConfPath(ruleId) }];
    case "block_ip_set":
      return [{ kind: "file", path: ipSetNftPath(ruleId) }];
  }
}

/** Cleanup ops for a single rule's owned targets. */
export function buildCleanupOps(ruleId: string, type: RuleType): Op[] {
  return ownedTargets(ruleId, type).map((t) => {
    if (t.kind === "uci") {
      return { type: "uci.delete", config: t.config, section: t.section };
    }
    return { type: "file.delete", path: t.path };
  });
}

/**
 * Build the device-agent ops a single rule contributes when it's APPLIED.
 * Cleanup ops (deletes) are generated by `assembleDesired` so the device's
 * desired state is reproducible from the list of active rules each time.
 */
export function buildRuleOps(
  ruleId: string,
  type: RuleType,
  params: RuleParams,
): Op[] {
  switch (type) {
    case "pause_device": {
      const p = params as PauseDeviceParams;
      const section = `bt_${ruleId}`;
      return [
        // declare a named section so we can clean it up by name later
        { type: "uci.set", config: "firewall", section, value: "rule" },
        {
          type: "uci.set",
          config: "firewall",
          section,
          values: {
            name: ruleId,
            src: "lan",
            target: "REJECT",
            src_mac: p.mac,
            enabled: "1",
          },
        },
      ];
    }
    case "block_domains_network": {
      const p = params as BlockDomainsParams;
      // Emit both A (0.0.0.0) and AAAA (::) blocks. Without the AAAA entry,
      // dnsmasq returns NXDOMAIN/0.0.0.0 for A but FORWARDS AAAA upstream —
      // so any client with IPv6 connectivity (modern phones especially)
      // still reaches the host.
      const entries: string[] = [];
      for (const d of p.domains) {
        entries.push(`/${d}/0.0.0.0`);
        entries.push(`/${d}/::`);
      }
      return [
        {
          type: "uci.add_list",
          config: "dhcp",
          section: "@dnsmasq[0]",
          option: "address",
          list: entries,
        },
      ];
    }
    case "block_managed_list": {
      // OpenWrt's dnsmasq init reads /tmp/dnsmasq.cfg*.d/ but NOT
      // /etc/dnsmasq.d/ unless we add `confdir` to /etc/config/dhcp first.
      // We set it idempotently as part of every managed-list rule.
      // Structural placeholder for the file content — filled in at assembly
      // time by materializeOps() (we don't store a 1MB blob in account_rules
      // or chat_sessions.pending_proposal).
      return [
        {
          type: "uci.set",
          config: "dhcp",
          section: "@dnsmasq[0]",
          option: "confdir",
          value: "/etc/dnsmasq.d",
        },
        {
          type: "file.write",
          path: managedListConfPath(ruleId),
          content: "",
          mode: "644",
        },
      ];
    }
    case "block_ip_set": {
      // Structural placeholder — content is filled in at assembly time
      // by materializeOps() (fresh fetch of the IP list).
      return [
        {
          type: "file.write",
          path: ipSetNftPath(ruleId),
          content: "",
          mode: "644",
        },
        { type: "service", name: "firewall", action: "reload" },
      ];
    }
    case "force_router_dns": {
      // Three firewall sections:
      //   bt_<id>_t  — DNAT redirect for LAN tcp/53  → the router's own dnsmasq
      //   bt_<id>_u  — DNAT redirect for LAN udp/53  → same
      //   bt_<id>_dot — REJECT LAN → wan tcp/853 (DNS over TLS)
      //
      // Without dest_ip the redirect target is the router itself (fw4
      // resolves it to the lan-side address). The src='lan' scope means
      // router-originated DNS queries (dnsmasq forwarding upstream) are
      // never matched — only client traffic.
      //
      // DoH (HTTPS on 443) isn't blocked here — that needs a separate
      // policy (block known DoH endpoint IPs + DoH bootstrap domains).
      // Plain DNS coverage is the 90% win; DoH bypass is a follow-up.
      const tcp = `bt_${ruleId}_t`;
      const udp = `bt_${ruleId}_u`;
      const dot = `bt_${ruleId}_dot`;
      return [
        // tcp/53 redirect
        { type: "uci.set", config: "firewall", section: tcp, value: "redirect" },
        {
          type: "uci.set",
          config: "firewall",
          section: tcp,
          values: {
            name: `bt-dns-tcp-${ruleId}`,
            src: "lan",
            proto: "tcp",
            src_dport: "53",
            dest_port: "53",
            target: "DNAT",
            enabled: "1",
          },
        },
        // udp/53 redirect
        { type: "uci.set", config: "firewall", section: udp, value: "redirect" },
        {
          type: "uci.set",
          config: "firewall",
          section: udp,
          values: {
            name: `bt-dns-udp-${ruleId}`,
            src: "lan",
            proto: "udp",
            src_dport: "53",
            dest_port: "53",
            target: "DNAT",
            enabled: "1",
          },
        },
        // DoT block
        { type: "uci.set", config: "firewall", section: dot, value: "rule" },
        {
          type: "uci.set",
          config: "firewall",
          section: dot,
          values: {
            name: `bt-dot-${ruleId}`,
            src: "lan",
            dest: "wan",
            proto: "tcp",
            dest_port: "853",
            target: "REJECT",
            enabled: "1",
          },
        },
      ];
    }
  }
}

/**
 * Assemble the device's full `desired` ops array from the parent's active
 * rules. The pattern is "wipe-then-rebuild" so the result is idempotent:
 *
 *  1. Idempotent cleanup of anything we might have left from prior versions
 *     (delete every paused-device named section we've ever issued; clear the
 *     dnsmasq address list). The agent tolerates "Entry not found", so these
 *     are safe no-ops when nothing's there.
 *  2. Apply each active rule's ops in order.
 *  3. Append commits for the touched UCI configs + service reloads.
 */
// ---------------------------------------------------------------------------
// Managed-list sources — curated upstream blocklists Bri can apply by name.
// Each source has a canonical URL and a parser; we fetch on demand at apply /
// reset time and embed the resulting dnsmasq conf into a file.write op.
// ---------------------------------------------------------------------------

export const MANAGED_LIST_SOURCES = {
  "hagezi-anti-bypass": {
    label: "HaGeZi anti-bypass (VPN + DoH/DoT + Tor bootstrap + proxies)",
    // jsDelivr CDN-fronted — avoids the raw.githubusercontent rate limit.
    url:
      "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/doh-vpn-proxy-bypass-onlydomains.txt",
  },
} as const;

export type ManagedListSource = keyof typeof MANAGED_LIST_SOURCES;

/**
 * Fetch + parse a managed list to a clean domain array. Lines starting with
 * `#` or whitespace-only are dropped. We trust jsDelivr's CDN to handle
 * caching; we don't carry our own in-process cache because Vercel functions
 * are short-lived and per-invocation state doesn't persist anyway.
 */
export async function fetchManagedListDomains(
  source: ManagedListSource,
): Promise<string[]> {
  const cfg = MANAGED_LIST_SOURCES[source];
  if (!cfg) throw new Error(`unknown managed-list source: ${source}`);
  const res = await fetch(cfg.url, {
    headers: { "User-Agent": "braintech-bot/1.0 (+https://getbraintech.com)" },
  });
  if (!res.ok) throw new Error(`fetch ${source} failed: ${res.status}`);
  const text = await res.text();
  const domains: string[] = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    // dnsmasq accepts only the bare domain; reject anything fishy
    if (!/^[A-Za-z0-9._-]+$/.test(line)) continue;
    domains.push(line.toLowerCase());
  }
  return domains;
}

/** Build the dnsmasq conf-file contents (A + AAAA block per domain). */
export function dnsmasqBlockConf(domains: string[]): string {
  const lines: string[] = [
    "# Braintech — managed blocklist (auto-generated, do not edit)",
    `# ${domains.length} domains, A + AAAA each`,
    "",
  ];
  for (const d of domains) {
    lines.push(`address=/${d}/0.0.0.0`);
    lines.push(`address=/${d}/::`);
  }
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// IP-set sources — upstream feeds of IP addresses to firewall-block. Used by
// block_ip_set rules. Each source produces one set + one forward-hook chain
// in /etc/nftables.d/bt-<ruleId>.nft (auto-included by fw4 reload).
// ---------------------------------------------------------------------------

export const IP_SET_SOURCES = {
  "dibdot-doh-ipv4": {
    label: "DoH endpoint IPv4 addresses (dibdot)",
    url: "https://raw.githubusercontent.com/dibdot/DoH-IP-blocklists/master/doh-ipv4.txt",
    family: "ipv4" as const,
    default_dest_port: 443,
  },
  "dibdot-doh-ipv6": {
    label: "DoH endpoint IPv6 addresses (dibdot)",
    url: "https://raw.githubusercontent.com/dibdot/DoH-IP-blocklists/master/doh-ipv6.txt",
    family: "ipv6" as const,
    default_dest_port: 443,
  },
  "tor-exit-ipv4": {
    label: "Tor exit-node IPv4 addresses (torproject.org bulk list)",
    url: "https://check.torproject.org/torbulkexitlist",
    family: "ipv4" as const,
    default_dest_port: undefined, // Tor uses many ports → block any
  },
} as const;

export type IpSetSource = keyof typeof IP_SET_SOURCES;

const IPV4_RE = /^(?:\d{1,3}\.){3}\d{1,3}$/;
const IPV6_RE = /^[0-9a-fA-F:]+$/;

/**
 * Fetch + parse an IP-set source. Strips `#` comments and blank lines.
 * Validates each entry against a coarse regex appropriate for its family;
 * the kernel rejects truly malformed entries on `nft -f` so we don't need
 * to be strict here.
 */
export async function fetchIpSetEntries(
  source: IpSetSource,
): Promise<string[]> {
  const cfg = IP_SET_SOURCES[source];
  if (!cfg) throw new Error(`unknown ip-set source: ${source}`);
  const res = await fetch(cfg.url, {
    headers: { "User-Agent": "braintech-bot/1.0 (+https://getbraintech.com)" },
  });
  if (!res.ok) throw new Error(`fetch ${source} failed: ${res.status}`);
  const text = await res.text();
  const re = cfg.family === "ipv4" ? IPV4_RE : IPV6_RE;
  const out: string[] = [];
  for (const raw of text.split(/\r?\n/)) {
    // strip inline comments (`1.0.0.1  # cloudflare` → `1.0.0.1`)
    const line = raw.split("#")[0].trim();
    if (!line) continue;
    if (!re.test(line)) continue;
    out.push(line);
  }
  return out;
}

/**
 * Build the nftables include file: one set + one forward-hook chain that
 * rejects packets whose destination matches. We hook at priority -10 so we
 * fire BEFORE fw4's main forward chain (priority 0) — kernel runs both
 * chains, ours rejects first if it matches.
 */
export function nftBlockIpSetFile(
  ruleId: string,
  family: "ipv4" | "ipv6",
  entries: string[],
  destPort?: number,
): string {
  const setName = `bt_${ruleId}_set`;
  const chainName = `bt_${ruleId}`;
  const addrType = family === "ipv4" ? "ipv4_addr" : "ipv6_addr";
  const ipMatch = family === "ipv4" ? "ip daddr" : "ip6 daddr";
  const portClause = destPort != null ? ` tcp dport ${destPort}` : "";
  const lines: string[] = [];
  lines.push(`# Braintech — managed IP blocklist (auto-generated, do not edit)`);
  lines.push(`# ${entries.length} entries, family=${family}, dest_port=${destPort ?? "any"}`);
  lines.push(``);
  lines.push(`set ${setName} {`);
  lines.push(`    type ${addrType}`);
  lines.push(`    flags interval`);
  if (entries.length > 0) {
    // nft accepts a comma-separated braced literal; long lists wrap fine.
    lines.push(`    elements = {`);
    // chunk 8 per line so the file is readable in logread/cat
    for (let i = 0; i < entries.length; i += 8) {
      const chunk = entries.slice(i, i + 8).join(", ");
      const isLast = i + 8 >= entries.length;
      lines.push(`        ${chunk}${isLast ? "" : ","}`);
    }
    lines.push(`    }`);
  }
  lines.push(`}`);
  lines.push(``);
  lines.push(`chain ${chainName} {`);
  lines.push(`    type filter hook forward priority -10; policy accept;`);
  lines.push(`    ${ipMatch} @${setName}${portClause} reject comment "bt:${ruleId}"`);
  lines.push(`}`);
  return lines.join("\n") + "\n";
}

/**
 * Materialize a rule into the actual ops the agent will run. For most rule
 * types this is just the structural ops from buildRuleOps. For rules that
 * carry an upstream-fetched blob (block_managed_list, block_ip_set), this
 * fetches the source and inlines its content into the relevant file.write
 * op — everything else (uci.set, service reload) flows through unchanged.
 */
export async function materializeOps(rule: AccountRule): Promise<Op[]> {
  if (rule.rule_type === "block_managed_list") {
    const p = rule.params as BlockManagedListParams;
    const domains = await fetchManagedListDomains(p.source);
    const conf = dnsmasqBlockConf(domains);
    const path = managedListConfPath(rule.rule_id);
    return rule.ops.map((o) =>
      o.type === "file.write" && o.path === path ? { ...o, content: conf } : o,
    );
  }
  if (rule.rule_type === "block_ip_set") {
    const p = rule.params as BlockIpSetParams;
    const cfg = IP_SET_SOURCES[p.source];
    const entries = await fetchIpSetEntries(p.source);
    const content = nftBlockIpSetFile(
      rule.rule_id,
      cfg.family,
      entries,
      p.dest_port ?? cfg.default_dest_port,
    );
    const path = ipSetNftPath(rule.rule_id);
    return rule.ops.map((o) =>
      o.type === "file.write" && o.path === path ? { ...o, content } : o,
    );
  }
  return rule.ops;
}

/**
 * Build the device's full desired ops from every rule ever issued (active
 * or not). The pattern is "wipe-then-rebuild":
 *
 *   1. Cleanup every named UCI section any rule has ever owned + always
 *      wipe the dnsmasq address list. The agent's uci.delete is tolerant
 *      of missing entries, so it's safe to delete things that don't exist.
 *   2. Re-emit ops for ACTIVE rules only.
 *   3. Commit firewall + dhcp and reload firewall + dnsmasq. We always
 *      touch both configs above (the cleanup writes to both), so we must
 *      always commit AND reload both — otherwise the running daemon holds
 *      stale state from before the cleanup.
 *
 * Pass ALL rules (active and inactive). Inactive rules contribute cleanup
 * ops only; active rules contribute cleanup + apply. This makes the desired
 * state a pure function of (allRules) with no path-dependence.
 */
export function assembleDesired(allRules: AccountRule[]): Op[] {
  const ops: Op[] = [];

  // (1) cleanup — every owned section across every rule we know about.
  for (const r of allRules) {
    for (const o of buildCleanupOps(r.rule_id, r.rule_type)) ops.push(o);
  }
  // Always wipe the dnsmasq address list — domain rules own it as a shared
  // resource and we rebuild it from scratch each time.
  ops.push({ type: "uci.delete", config: "dhcp", section: "@dnsmasq[0]", option: "address" });

  // (2) apply each active rule's ops
  for (const r of allRules) {
    if (!r.active) continue;
    for (const o of r.ops) ops.push(o);
  }

  // (3) commit + reload firewall + dhcp/dnsmasq unconditionally
  ops.push({ type: "uci.commit", config: "firewall" });
  ops.push({ type: "uci.commit", config: "dhcp" });
  ops.push({ type: "service", name: "firewall", action: "reload" });
  ops.push({ type: "service", name: "dnsmasq", action: "reload" });

  return ops;
}
