import { randomBytes } from "node:crypto";

/** A single agent operation (mirrors the device-agent grammar). */
export type Op = {
  type: string;
  config?: string;
  section?: string;
  section_type?: string;
  option?: string;
  value?: string;
  values?: Record<string, string>;
  list?: string[];
  name?: string;
  action?: string;
};

export type RuleType = "pause_device" | "block_domains_network";

export type PauseDeviceParams = { mac: string; client_name?: string };
export type BlockDomainsParams = { domains: string[] };
export type RuleParams = PauseDeviceParams | BlockDomainsParams;

export interface AccountRule {
  rule_id: string;
  rule_type: RuleType;
  params: RuleParams;
  ops: Op[];
  name: string;
  summary?: string;
  active: boolean;
}

export function newRuleId(prefix: "pause" | "domains"): string {
  return `${prefix}_${randomBytes(4).toString("hex")}`;
}

/**
 * Build the device-agent ops a single rule contributes when it's APPLIED.
 * Cleanup ops (deletes) are generated by `assembleDesired` so the device's
 * desired state is reproducible from the list of active rules each time.
 */
export function buildRuleOps(
  ruleId: string,
  type: RuleType,
  params: RuleParams,
): Op[] {
  switch (type) {
    case "pause_device": {
      const p = params as PauseDeviceParams;
      const section = `bt_${ruleId}`;
      return [
        // declare a named section so we can clean it up by name later
        { type: "uci.set", config: "firewall", section, value: "rule" },
        {
          type: "uci.set",
          config: "firewall",
          section,
          values: {
            name: ruleId,
            src: "lan",
            target: "REJECT",
            src_mac: p.mac,
            enabled: "1",
          },
        },
      ];
    }
    case "block_domains_network": {
      const p = params as BlockDomainsParams;
      // Emit both A (0.0.0.0) and AAAA (::) blocks. Without the AAAA entry,
      // dnsmasq returns NXDOMAIN/0.0.0.0 for A but FORWARDS AAAA upstream —
      // so any client with IPv6 connectivity (modern phones especially)
      // still reaches the host.
      const entries: string[] = [];
      for (const d of p.domains) {
        entries.push(`/${d}/0.0.0.0`);
        entries.push(`/${d}/::`);
      }
      return [
        {
          type: "uci.add_list",
          config: "dhcp",
          section: "@dnsmasq[0]",
          option: "address",
          list: entries,
        },
      ];
    }
  }
}

/**
 * Assemble the device's full `desired` ops array from the parent's active
 * rules. The pattern is "wipe-then-rebuild" so the result is idempotent:
 *
 *  1. Idempotent cleanup of anything we might have left from prior versions
 *     (delete every paused-device named section we've ever issued; clear the
 *     dnsmasq address list). The agent tolerates "Entry not found", so these
 *     are safe no-ops when nothing's there.
 *  2. Apply each active rule's ops in order.
 *  3. Append commits for the touched UCI configs + service reloads.
 */
export function assembleDesired(
  allKnownPauseRuleIds: string[],
  activeRules: AccountRule[],
): Op[] {
  const ops: Op[] = [];
  const configs = new Set<string>();
  const services = new Set<string>();

  // (1) cleanup of prior state — ALWAYS run all cleanups every time. The
  //     agent's uci.delete is tolerant of "Entry not found", so deleting
  //     things that don't exist is a no-op. This keeps the desired state
  //     a pure function of activeRules with no path-dependence.
  for (const id of allKnownPauseRuleIds) {
    ops.push({ type: "uci.delete", config: "firewall", section: `bt_${id}` });
  }
  ops.push({ type: "uci.delete", config: "dhcp", section: "@dnsmasq[0]", option: "address" });

  // (2) apply each active rule's ops
  for (const r of activeRules) {
    for (const o of r.ops) {
      ops.push(o);
      if (o.config) configs.add(o.config);
    }
  }
  // cleanup itself always touches firewall + dhcp, so those configs must
  // be committed and their owning services reloaded every time — otherwise
  // a transition from "has rule" → "no rules" would leave the running
  // service holding stale state from disk.
  configs.add("firewall");
  configs.add("dhcp");

  // (3) commit + reload — always reload the services whose configs we
  //     touched (firewall, dnsmasq), so removed rules actually disappear
  //     from the kernel/daemon ruleset, not just from the on-disk config.
  for (const c of configs) ops.push({ type: "uci.commit", config: c });
  if (configs.has("firewall")) services.add("firewall");
  if (configs.has("dhcp")) services.add("dnsmasq");
  for (const s of services) ops.push({ type: "service", name: s, action: "reload" });

  return ops;
}
