package main

// Code generated by scripts/gen-tracker-denylist.mjs — DO NOT EDIT BY HAND.
// Source: DuckDuckGo Tracker Radar (https://raw.githubusercontent.com/duckduckgo/tracker-radar/main/domains/US), generated 2026-08-05.
// Re-run the script to refresh; see its header for the selection rules.
//
// Ad/analytics/pixel hosts living inside app zones the usage classifier
// attributes (tr.snapchat.com etc). A DNS query to one of these means
// "a web page is phoning home to this company's ad system", not "the
// kid is using this app" — so classifyApp and the quota recorders skip
// them.
var trackerDomains = map[string]bool{
	"alb.reddit.com": true, // in reddit.com zone
	"analytics.tiktok.com": true, // in tiktok.com zone
	"analytics.twitter.com": true, // in twitter.com zone
	"fcmatch.youtube.com": true, // in youtube.com zone
	"intg.snapchat.com": true, // in snapchat.com zone
	"pi.reddit.com": true, // in reddit.com zone
	"pixel-config.reddit.com": true, // in reddit.com zone
	"spade.twitch.tv": true, // in twitch.tv zone
	"tr.snapchat.com": true, // in snapchat.com zone
	"tr6.snapchat.com": true, // in snapchat.com zone
	"tracking.epicgames.com": true, // in epicgames.com zone
}

// isTrackerDomain reports whether the queried name is (or is under) a
// known tracking endpoint. Same suffix semantics as matchesAny.
func isTrackerDomain(domain string) bool {
	d := normalizeDomain(domain)
	if trackerDomains[d] {
		return true
	}
	for t := range trackerDomains {
		if len(d) > len(t) && d[len(d)-len(t)-1] == '.' && d[len(d)-len(t):] == t {
			return true
		}
	}
	return false
}
